version: "3.8"

services:
  slurm:
    image: giovtorres/docker-centos7-slurm:21.08.6
    hostname: slurmctl
    container_name: slurmctl
    working_dir: /mlflow_mltf
    stdin_open: true
    tty: true
    environment:
      PYTHON: "3.9"
    volumes:
      - ./:/mlflow_mltf
