name: Push Docker Image

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  commit-docker-latest:
    runs-on: 
      - ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Build release distributions
        run: |
          echo -n $GH_TOKEN | docker login --password-stdin -u ${{ github.repository_owner }} ghcr.io
          ls -lah $HOME
          ls -lah
          echo $GH_TOKEN
          ./ci/mltf-container/build.sh -c -t ghcr.io/accre/mltf-gateway:latest
          docker push ghcr.io/accre/mltf-gateway:latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USER: ${{ github.repository_owner }}
